language:
    node_js
node_js:
    - 0.10
branches:
    only:
        - master

before_script:
    # install dependencies
    - gem update --system
    - gem install compass
    - npm install -g grunt-cli bower
script:
    # We want to gate on passing tests and a successful build
    - bower install
    - grunt staging

deploy:
    provider: s3
    access_key_id:
      secure: TMVA47aCJxdHhjsCEeVxagz7bm2qZRHBSyRogh4pCu/xqNzHK8F9v7ck+Mxtmu4IKHHXaVn1oDT1/B68ejrvtF385s9dc44GXTF2FGKHHuM8d+AtO5UIGRuFs1xeq9mxvGr52CnX9/RhP+Evk1APbEUxkSNjcUYP/7A7i09eMZ4=
    secret_access_key:
      secure: fotI8fAV0rUGf9KZF57HyBxBhW9uYkplNoMMiOmRTVv6++9zaaM4aNs4Im4xyZbigAFr4ghc7odaYOH4Zs2jBc8ouPS+BH+KDap8qKw8EfX2h5jwgm7CNt4OLdlpxmDJ464eB3SVPNQWLN/MyBFzxnFvVpaWMnaIji42ustvPr8=
    bucket: b2g-dashboard
